name: multitool
description: "A collection of project-independent Flutter/Dart extension methods and utilities"
version: 0.0.2
homepage: https://github.com/PlanterApp/multitool

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  screwdriver: ^5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0